import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/UI/navbar/Navbar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="mt-[40px]">
          {children}
          <footer className="bg-gray-800 text-white py-5 mt-8">
            <p className="text-center font-bold">
              hecho por cristian david roa
            </p>
            <ul className="flex justify-center items-center gap-3">
              <li>
                <Link
                  href="https://www.linkedin.com/in/devcris2023/"
                  className="text-blue-300"
                >
                  LinkedIn
                </Link>
              </li>
              <li>Email: curiosity.cdrr@gmail.com</li>
            </ul>
          </footer>
        </div>
      </body>
    </html>
  );
}
